[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pd-explain"
authors = [{name = "Amit Somech", email = "amitsomech@gmail.com"}]
dynamic = ["version", "description"]
